name: image_compression_flutter
description: Flutter image compression and resize for Mobile, Desktop and Web. Support format JPG, PNG, WEBP.
version: 1.0.4
homepage: https://github.com/eyro-labs/image_compression_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cross_file: ^0.3.3+4
  flutter_image_compress: ^2.1.0
  image_compression: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.co.eyro.image_compression_flutter
        pluginClass: ImageCompressionFlutterPlugin
      ios:
        pluginClass: ImageCompressionFlutterPlugin
      web:
        pluginClass: ImageCompressionFlutterWeb
        fileName: image_compression_flutter_web.dart
      macos:
        pluginClass: ImageCompressionFlutterPlugin
      windows:
        pluginClass: ImageCompressionFlutterPlugin
      linux:
        pluginClass: ImageCompressionFlutterPlugin
