name: image_compression_flutter
description: Flutter image compression and resize for Mobile, Desktop and Web. Support format JPG, PNG, WEBP.
version: 1.0.3
homepage: https://github.com/eyro-labs/image_compression_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cross_file: ^0.3.3+4
  flutter_image_compress: ^1.1.3
  image_compression: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: id.co.eyro.image_compression_flutter
        pluginClass: ImageCompressionFlutterPlugin
      ios:
        pluginClass: ImageCompressionFlutterPlugin
      web:
        pluginClass: ImageCompressionFlutterWeb
        fileName: image_compression_flutter_web.dart
      macos:
        pluginClass: ImageCompressionFlutterPlugin
      windows:
        pluginClass: ImageCompressionFlutterPlugin
      linux:
        pluginClass: ImageCompressionFlutterPlugin
